export const data = [
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },

  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },

  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    task: "Bring cake",
    amount: "2000",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
  {
    from: "Shivansh Gupta",
    to: "Himalaya Gupta",
    amount: "2000",
    task: "Bring cake",
    date: "20 Dec 2021, 12:55PM",
  },
];
